title = "Active Nation Day"
baseURL = "https://activenationday.com"
languageCode = "en-au"
theme = "and"

MetaDataFormat = "toml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 10 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = "UA-16103240-9"
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  subtitle = "subtitle"
  metadesc = "Join us on 24 September 2017 for Lorna Jane's Active Nation Day and become part of our global movement to create a more active future."
  description = "YOUR MOVE MATTERS"
  faceboook = ""
  twitter = "https://twitter.com/lornajane"
  instagram = ""
  youtube = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-white"
  featured_image = ""
